### ISSUE TITLE
About the test

### ISSUE THREAD

**Issue by ghost** [Hi-Angel/notes-backup#2]
I guess "mount -t cifs" is the reason why SMB so slow.
SMB v1 (CIFS) is much slower than SMB v3
https://photographylife.com/afp-vs-nfs-vs-smb-performance

**Comment by Hi-Angel** [comment]
> I guess "mount -t cifs" is the reason why SMB so slow.
> SMB v1 (CIFS) is much slower than SMB v3

Thanks for your comment! I did some research, so:

Manual for `mount.cifs` says the following, quoting:

> The default since v4.13.5 is for the client and server to negotiate the highest possible version greater than or equal to 2.1. In kernels prior to v4.13, the default was 1.0. For kernels between v4.13 and v4.13.5 the default is 3.0.

The Ubuntu machine had kernel 4.19, whereas the Archlinux one I don't know but it must have been 5.4 or higher.

[SMB3 was introduced in 2012 year](https://en.wikipedia.org/wiki/Server_Message_Block#SMB_3.0), which is very long ago.

What we can infer from that is that upon executing `mount -t cifs` the highest supported SAMBA version was communicated, and there is no way it could have been below 3.0. I'd even say it most probably was 3.1.1, although I am not completely sure on that one.

> https://photographylife.com/afp-vs-nfs-vs-smb-performance

It's indeed curious why this post has so different results. But as a wild guess, implementation matters. I know that at least on Linux parts of SMB and NFS protocols are implemented in kernel *(see for example [this paragraph](https://kernelnewbies.org/Linux_5.11#File_systems), the points NFS and CIFS)*. So, given the author tested on Mac OS system, their tests surely have used different implementations of both NFS and SMB.

What that means is that we can't even say if their SMB implementation is better *(I doubt it given how much investments go to Linux from server/cloud fields)* or if their NFS implementation worse, or is it they had bad implementations for both NFS and SMB, or whatever other theory we can have here.

**Comment by Hi-Angel** [comment]
> > https://photographylife.com/afp-vs-nfs-vs-smb-performance
> 
> It's indeed curious why this post has so different results. But as a wild guess, implementation matters. I know that at least on Linux parts of SMB and NFS protocols are implemented in kernel _(see for example [this paragraph](https://kernelnewbies.org/Linux_5.11#File_systems), the points NFS and CIFS)_. So, given the author tested on Mac OS system, their tests surely have used different implementations of both NFS and SMB.

Oh, btw, there's another important thing to note: their test is different as well. From what I understand they tested speed of uploading/downloading a file.

I was testing something else. In my case there are many files in shared directory, and I was interested in accessing many of them. Like, for example, I have shared a git repo, and I want to see `git status` remotely. This might test quite a different codepath compared to just one file, because there's a directory tree, and it's a question of how good implementation in traversing it, in caching some parts of it, etc.

**Comment by Hi-Angel** [comment]
In absence of any follow-up from the OP, I presume I fully answered the issue. Closing. Feel free to reopen if there's new information.
